[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { NODE_ENV = "production" }

[environments.production.deploy]
startCommand = "python bot.py"

# Configurações de saúde do serviço
[environments.production.healthcheck]
path = "/health"
interval = 30
timeout = 10
retries = 3

# Configurações de recursos
[environments.production.resources]
memory = 512
cpu = 0.5

# Variáveis de ambiente obrigatórias
[environments.production.variables]
PORT = "8000"
PYTHON_VERSION = "3.11.7"